version: '3'
services:
  web:
    build: .
    ports:
     - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://deploy@postgres/slackchamp
  postgres:
    image: "postgres:9.6.5-alpine"
    environment:
      POSTGRES_USER: deploy
      POSTGRES_DB: slackchamp
